plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 35
    namespace 'org.woheller69.audiometry'
    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        minSdkVersion 23
        targetSdk 35
        versionCode 220
        versionName "2.2"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'net.lingala.zip4j:zip4j:2.9.1'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.github.woheller69:FreeDroidWarn:V1.3'
}
